[tool]
[tool.poetry]
authors = ["ErdemBey"]
description = "Siri Userbot Yeni Otomatik İnstaller"
name = "SiriUserBot_Installer"
version = "3.0"
[tool.poetry.dependencies]
bs4 = "*"
gitpython = "*"
heroku3 = "*"
python = "^3.8"
requests = "*"
rich = "*"
telethon = "*"
